package com.example.vref_solutions_tablet_application.Enums

enum class PopUpType {
    CHANGE_EVENT, SWITCH_CAMERA_1, SWITCH_CAMERA_2, ADD_EVENT, EXIT_TRAINING, EDIT_USER, NEW_USER, NEW_ORGANIZATION, EDIT_EVENT, PRESCRIBED_EVENT_INFO
}